version: 2.1
orbs:
  docker: checkmoney/docker@1.1.0
  deploy: checkmoney/deploy@1.2.3
workflows:
  version: 2
  build:
    jobs:
      - docker/build_push:
          org_name: 'igorkamyshev'
          image_name: 'yt-listen'
          image_version: CIRCLE_TAG
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy/roll_out:
          notify_user: '65400792'
          ssh_user: SSH_USER
          ssh_host: SSH_HOST
          org_name: 'igorkamyshev'
          image_name: 'yt-listen'
          image_version: CIRCLE_TAG
          path_to_app: PATH_TO_APP
          apply_post_install: true
          post_install_script: 'yarn evolutions -y'
          container_name: 'yt_listen'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - docker/build_push
